server:
  port: 9039

spring:
  datasource:
    password: AHdms520
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://172.16.1.190:3306/svs_web?serverTimezone=UTC&characterEncoding=utf-8
  main:
    allow-bean-definition-overriding: true

mybatis-plus:
  global-config:
    db-config:
      id-type: INPUT
  mapper-locations: classpath:mapper/*.xml